[versions]
# libraries
annotations = "24.0.1"

# plugins
changelog = "2.2.0"
gradleIntelliJPlugin = "1.15.0"
gradleGrammarkitPlugin = "2022.3.1"
qodana = "0.1.13"
kover = "0.7.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
gradleGrammarkitPlugin = { id = "org.jetbrains.grammarkit", version.ref = "gradleGrammarkitPlugin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }